# Generated by Django 4.2.29 on 2026-04-06 03:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. 2025-2026', max_length=20, unique=True, verbose_name='Academic Year')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_current', models.BooleanField(default=False, help_text='Mark as the active academic year', verbose_name='Current Year')),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_hours_override', models.PositiveIntegerField(blank=True, help_text='Override subject default weekly hours for this offering', null=True, verbose_name='Weekly Hours Override')),
            ],
            options={
                'verbose_name': 'Course Offering',
                'verbose_name_plural': 'Course Offerings',
                'ordering': ['section', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name, e.g. Computer Science & Engineering', max_length=100, verbose_name='Department Name')),
                ('code', models.CharField(help_text='Short code, e.g. CSE', max_length=10, unique=True, verbose_name='Department Code')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(help_text='e.g. CSE001', max_length=20, unique=True, verbose_name='Faculty ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Last Name')),
                ('initials', models.CharField(blank=True, help_text='e.g. Dr. RK', max_length=10, verbose_name='Initials')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('designation', models.CharField(choices=[('PROF', 'Professor'), ('ASSOC_PROF', 'Associate Professor'), ('ASST_PROF', 'Assistant Professor'), ('HOD', 'Head of Department'), ('VISITING', 'Visiting Faculty')], default='ASST_PROF', max_length=15, verbose_name='Designation')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_members', to='SchedulerApp.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculty Members',
                'ordering': ['department', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Artificial Intelligence & Machine Learning', max_length=100, verbose_name='Program Name')),
                ('code', models.CharField(help_text='e.g. AIML', max_length=10, unique=True, verbose_name='Program Code')),
                ('duration_years', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Duration (Years)')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='SchedulerApp.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='e.g. A101, LAB-3', max_length=20, verbose_name='Room Number')),
                ('name', models.CharField(blank=True, help_text='Optional friendly name', max_length=80, verbose_name='Room Name')),
                ('building', models.CharField(blank=True, max_length=50, verbose_name='Building')),
                ('seating_capacity', models.PositiveIntegerField(default=60, verbose_name='Seating Capacity')),
                ('room_type', models.CharField(choices=[('CLASSROOM', 'Classroom'), ('LAB', 'Laboratory'), ('SEMINAR', 'Seminar Hall'), ('AUDITORIUM', 'Auditorium')], default='CLASSROOM', max_length=15, verbose_name='Room Type')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['building', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. A, B, C', max_length=5, verbose_name='Section Name')),
                ('year_of_study', models.PositiveIntegerField(choices=[(1, 'I Year'), (2, 'II Year'), (3, 'III Year'), (4, 'IV Year')], verbose_name='Year of Study')),
                ('semester', models.PositiveIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')], verbose_name='Semester')),
                ('strength', models.PositiveIntegerField(default=60, verbose_name='Student Strength')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='SchedulerApp.academicyear', verbose_name='Academic Year')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='SchedulerApp.department', verbose_name='Department')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='SchedulerApp.program', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['year_of_study', 'department', 'program', 'name'],
                'unique_together': {('name', 'year_of_study', 'semester', 'program', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. CS3491', max_length=15, unique=True, verbose_name='Subject Code')),
                ('name', models.CharField(help_text='Full name, e.g. Machine Learning', max_length=120, verbose_name='Subject Name')),
                ('short_name', models.CharField(help_text='Abbreviation for timetable cells, e.g. ML', max_length=15, verbose_name='Short Name')),
                ('subject_type', models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Laboratory'), ('ELECTIVE', 'Elective'), ('COMMON', 'Common / Audit')], default='THEORY', max_length=10, verbose_name='Subject Type')),
                ('credits', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Credits')),
                ('weekly_hours', models.PositiveIntegerField(default=4, help_text='Total weekly contact hours', verbose_name='Weekly Hours')),
                ('max_students', models.PositiveIntegerField(default=60, verbose_name='Maximum Students')),
                ('lab_duration_slots', models.PositiveIntegerField(default=1, help_text='Number of consecutive slots for lab sessions (1 for theory)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Lab Duration (Slots)')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveIntegerField(help_text='Order within the day (1, 2, 3…)', verbose_name='Slot Number')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3, verbose_name='Day')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('slot_type', models.CharField(choices=[('REGULAR', 'Regular Class'), ('LAB', 'Lab Block'), ('BREAK', 'Break'), ('LUNCH', 'Lunch')], default='REGULAR', max_length=10, verbose_name='Slot Type')),
                ('label', models.CharField(blank=True, help_text='e.g. Period 1, Lunch Break', max_length=40, verbose_name='Label')),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'ordering': ['day', 'slot_number'],
                'unique_together': {('day', 'slot_number')},
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10, verbose_name='Status')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generated At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('fitness_score', models.FloatField(default=0.0, help_text='Quality score from genetic algorithm (1.0 = perfect)', verbose_name='Fitness Score')),
                ('generations_run', models.PositiveIntegerField(default=0, verbose_name='Generations Run')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='SchedulerApp.academicyear', verbose_name='Academic Year')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='SchedulerApp.section', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Timetable',
                'verbose_name_plural': 'Timetables',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('TIMETABLE_ADMIN', 'Timetable Admin'), ('HOD', 'Head of Department'), ('FACULTY', 'Faculty'), ('STUDENT', 'Student')], default='STUDENT', max_length=20, verbose_name='Role')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='SchedulerApp.department', verbose_name='Department')),
                ('faculty_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='SchedulerApp.faculty', verbose_name='Linked Faculty')),
                ('section', models.ForeignKey(blank=True, help_text='For students: their enrolled section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='SchedulerApp.section', verbose_name='Section')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('REGULAR', 'Regular'), ('LAB', 'Lab')], default='REGULAR', max_length=10, verbose_name='Entry Type')),
                ('duration_slots', models.PositiveIntegerField(default=1, help_text='Number of consecutive slots (>1 for labs)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Duration (Slots)')),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='SchedulerApp.courseoffering', verbose_name='Course Offering')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='SchedulerApp.faculty', verbose_name='Faculty')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='SchedulerApp.room', verbose_name='Room')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='SchedulerApp.timeslot', verbose_name='Time Slot')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='SchedulerApp.timetable', verbose_name='Timetable')),
            ],
            options={
                'verbose_name': 'Timetable Entry',
                'verbose_name_plural': 'Timetable Entries',
                'ordering': ['timetable', 'time_slot'],
            },
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='faculty',
            field=models.ManyToManyField(blank=True, help_text='Faculty who can teach this subject for this section', related_name='course_offerings', to='SchedulerApp.faculty', verbose_name='Assigned Faculty'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='SchedulerApp.section', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='SchedulerApp.subject', verbose_name='Subject'),
        ),
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together={('subject', 'section')},
        ),
    ]
